"""add_chatbot_enabled_plan_to_users

Revision ID: 7d98387ab6f7
Revises: 13c4ba78de7c
Create Date: 2026-03-24 00:54:13.623814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7d98387ab6f7'
down_revision: Union[str, Sequence[str], None] = '13c4ba78de7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('chatbot_enabled', sa.Integer(), server_default='1', nullable=False))
    op.add_column('users', sa.Column('plan', sa.String(length=20), server_default='trial', nullable=False))
    op.add_column('users', sa.Column('plan_expires_at', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'users', ['chatbot_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'plan_expires_at')
    op.drop_column('users', 'plan')
    op.drop_column('users', 'chatbot_enabled')
    # ### end Alembic commands ###
