"""adding chatbot_name table

Revision ID: 8c82060bd51e
Revises: ad1d0f0600a2
Create Date: 2026-01-20 14:48:56.433405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8c82060bd51e'
down_revision: Union[str, Sequence[str], None] = 'ad1d0f0600a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatbot_name',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(length=100), nullable=False),
    sa.Column('chatbot_name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['users.client_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chatbot_name_client_id'), 'chatbot_name', ['client_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chatbot_name_client_id'), table_name='chatbot_name')
    op.drop_table('chatbot_name')
    # ### end Alembic commands ###
