"""Initial migration with users, chats, domains, tasks

Revision ID: 95def46410b1
Revises: 
Create Date: 2025-11-06 12:24:22.486699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '95def46410b1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.String(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.Column('country_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('admin_override', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chats_client_session', 'chats', ['client_id', 'session_id'], unique=False)
    op.create_index('idx_chats_is_active', 'chats', ['is_active'], unique=False)
    op.create_index(op.f('ix_chats_client_id'), 'chats', ['client_id'], unique=False)
    op.create_index(op.f('ix_chats_session_id'), 'chats', ['session_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('client_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('info', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.String(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.Column('updated_at', sa.String(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tasks_client', 'tasks', ['client_id'], unique=False)
    op.create_index(op.f('ix_tasks_client_id'), 'tasks', ['client_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mobile', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('chatbot_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_client_id'), 'users', ['client_id'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('domain_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('client_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chatbot_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.String(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['users.client_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_domain_mappings_domain', 'domain_mappings', ['domain'], unique=False)
    op.create_index(op.f('ix_domain_mappings_domain'), 'domain_mappings', ['domain'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_domain_mappings_domain'), table_name='domain_mappings')
    op.drop_index('idx_domain_mappings_domain', table_name='domain_mappings')
    op.drop_table('domain_mappings')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_client_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tasks_client_id'), table_name='tasks')
    op.drop_index('idx_tasks_client', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_chats_session_id'), table_name='chats')
    op.drop_index(op.f('ix_chats_client_id'), table_name='chats')
    op.drop_index('idx_chats_is_active', table_name='chats')
    op.drop_index('idx_chats_client_session', table_name='chats')
    op.drop_table('chats')
    # ### end Alembic commands ###
