"""Initial MariaDB migration

Revision ID: d0530e86bef0
Revises: 
Create Date: 2025-11-07 03:23:23.452435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd0530e86bef0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(length=100), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('country_code', sa.String(length=10), nullable=False),
    sa.Column('admin_override', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Integer(), server_default='1', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chats_client_session', 'chats', ['client_id', 'session_id'], unique=False)
    op.create_index('idx_chats_is_active', 'chats', ['is_active'], unique=False)
    op.create_index(op.f('ix_chats_client_id'), 'chats', ['client_id'], unique=False)
    op.create_index(op.f('ix_chats_session_id'), 'chats', ['session_id'], unique=False)
    op.create_table('domain_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('client_id', sa.String(length=100), nullable=False),
    sa.Column('chatbot_key', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_domain_mappings_domain', 'domain_mappings', ['domain'], unique=False)
    op.create_index(op.f('ix_domain_mappings_domain'), 'domain_mappings', ['domain'], unique=True)
    op.create_table('tasks',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('client_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('info', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tasks_client', 'tasks', ['client_id'], unique=False)
    op.create_index(op.f('ix_tasks_client_id'), 'tasks', ['client_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('client_id', sa.String(length=100), nullable=False),
    sa.Column('chatbot_key', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_client_id'), 'users', ['client_id'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_client_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tasks_client_id'), table_name='tasks')
    op.drop_index('idx_tasks_client', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_domain_mappings_domain'), table_name='domain_mappings')
    op.drop_index('idx_domain_mappings_domain', table_name='domain_mappings')
    op.drop_table('domain_mappings')
    op.drop_index(op.f('ix_chats_session_id'), table_name='chats')
    op.drop_index(op.f('ix_chats_client_id'), table_name='chats')
    op.drop_index('idx_chats_is_active', table_name='chats')
    op.drop_index('idx_chats_client_session', table_name='chats')
    op.drop_table('chats')
    # ### end Alembic commands ###
